engines:
  cppcheck:
    enabled: true
    config:
      check: all
      project: project.json
      language: c
      stds:
        - c89
      platform: unix64
      defines:
      - "_BSD_SOURCE"
      max_configs: 42
      inconclusive: false
