
matrix:
  fast_finish: true
  sudo: true
  include:
    - language: c
      script:
        - sudo apt-get install gcc-multilib
        - make
    - language: c
      script:
        - sudo apt-get install gcc-multilib
        - make test
    - language: c
      script:
        - sudo apt-get install gcc-multilib
        - make clicoverage
      after_success:
        - bash <(curl -s https://codecov.io/bash)
